### ISSUE TITLE
Research prerequisite kovarex-enrichment-process breaks artillery-atomics

### ISSUE THREAD

**Issue by Inrixia** [More-Wrong/Factorio-True-Nukes#15]
Unsure why specifically but currently playing in a modpack with Space Exploration and `artillery-atomics` is un researchable if the `kovarex-enrichment-process` is added as a prerequisite making progression impossible.

**Comment by More-Wrong** [comment]
Hi, that would be the fix, but as far as I can tell, the issue doesn't lie with base SE nor the SE official modpack, so doing the changes under SE would break the mod for people playing with just SE.
I'll work with you on finding the offending mod in the issue you raised.

**Comment by More-Wrong** [comment]
As I said in your PR, from my testing there don't seem to be any issues in base SE. 
What modpack/mods are you using - particularly those which change the nuclear cycle and would normally remove kovarex?

**Comment by Inrixia** [comment]
Ok so I have extracted and looked for `kovarex-enrichment-process` in all the mods currently installed and it looks like its [Nuclear Fuel](https://mods.factorio.com/mod/Nuclear%20Fuel) which by default disables `kovarex-enrichment-process` and its research.

So the simple fix is to check if the research is also enabled in the SE fixes

I have updated the PR with the changes. Let me know if there are any other checks that are needed.

<details>
<summary>Mod List</summary>

```json
[
	"base",
	"aai-containers",
	"aai-industry",
	"aai-signal-transmission",
	"advanced-portable-reactor",
	"alien-biomes",
	"alien-biomes-hr-terrain",
	"artillery-bombardment-remote",
	"AutoDeconstruct",
	"Automatic_Coupling_System",
	"Automatic_Train_Painter",
	"big-data-string",
	"bigger-artillery",
	"BlueprintSignals",
	"Bottleneck",
	"bullet-trails",
	"cargo-ships",
	"cargo-ships-graphics",
	"combat-mechanics-overhaul",
	"CopyPasteModules",
	"DeathNotice",
	"Dirt_Path",
	"Enhanced_Map_Colors",
	"equipment-gantry",
	"even-distribution",
	"Factorissimo2",
	"factoryplanner",
	"FARL-fixed-se",
	"Flammable_Oils_QUICKFIX",
	"FlashlightOnOff",
	"flib",
	"Flow Control",
	"FNEI",
	"GCKI",
	"GhostScanner",
	"glutenfree-ltn-thought-bubble",
	"Induction Charging",
	"informatron",
	"jetpack",
	"Kux-BlueprintExtensions",
	"Kux-CoreLib",
	"lightorio",
	"LogiNetChannels",
	"LogisticRequestHinter",
	"LogisticTrainNetwork",
	"MushroomCloud-patched",
	"nicefill",
	"Noxys_Multidirectional_Trains",
	"Noxys_Trees",
	"Nuclear Fuel",
	"nuclear_train",
	"original-music-hd-reloaded",
	"OverloadedTrains11",
	"PavementDriveAssistContinued",
	"Portable_power",
	"ProgressiveRunningRevived",
	"pump",
	"QuickItemSearch",
	"RateCalculator",
	"RealisticFlashlight",
	"RealisticReactorGlow",
	"Realistic_Heat_Glow",
	"RecipeBook",
	"recursive-blueprints",
	"research-progress",
	"Robot256Lib",
	"robot_attrition",
	"shield-projector",
	"simhelper",
	"space-exploration",
	"space-exploration-graphics",
	"space-exploration-graphics-2",
	"space-exploration-graphics-3",
	"space-exploration-graphics-4",
	"space-exploration-graphics-5",
	"space-exploration-menu-simulations",
	"space-exploration-postprocess",
	"Squeak Through",
	"SteamCracking",
	"Tapeline",
	"TrainDriver_A16_fix",
	"transparent-inventory",
	"True-Nukes",
	"True-Nukes-Graphics",
	"Underneathies",
	"UnminableBots",
	"upgrade-machines",
	"uranium_geiger",
	"VehicleWagon2",
	"vtk-armor-plating",
	"Warehousing",
	"Warheads",
	"Waterfill_v17",
	"what-is-it-really-used-for"
]
```
</details>

**Comment by More-Wrong** [comment]
Yeah, that's entirely correct - I just didn't realise the mods only disabled the tech instead of removing it entirely, and didn't propagate the fix into the SE code.

**Comment by More-Wrong** [comment]
The version 0.3.14 should include the changes
