### ISSUE TITLE
Incompatible with Plutonium Energy 1.5.0

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [More-Wrong/Factorio-True-Nukes#19]
Has been reported to me here: https://github.com/JohnTheCoolingFan/PlutoniumEnergy/issues/90

I managed to reproduce with just this mod.

**Comment by More-Wrong** [comment]
That's fine, I'll look into it tomorrow.

**Comment by More-Wrong** [comment]
Thanks, I've merged it, and I'm gonna test briefly before pushing an update to factorio mods

**Comment by More-Wrong** [comment]
Update is on mods now.
