### ISSUE TITLE
Compatibility with SE >= 0.6.118

### ISSUE THREAD

**Issue by wyphan** [More-Wrong/Factorio-True-Nukes#21]
Space Exploration version 0.6.118 adds weapon delivery cannon artillery icons. The corresponding icon for vanilla atomic bomb is added in Space Exploration Graphics Part 1 version 0.6.16. However, the default mod settings for True Nukes has vanilla atomic bomb disabled, resulting in this error message at mod load time:

![Screenshot from 2023-10-23 14-37-31](https://github.com/More-Wrong/Factorio-True-Nukes/assets/50928756/780ea049-010b-4be0-a5a1-5556aac8db35)

**Comment by daviscook477** [comment]
fyi this is an issue on the side of space exploration. we'll be releasing v0.6.119 with a fix for this. can close this please :)

**Comment by More-Wrong** [comment]
OK, thanks for confirming, I'll link the issues on factorio mods to here as well.
Please reopen if it's not fixed in v0.6.119, or any action is required on my side.
