### ISSUE TITLE
Unable to craft 3-stage atomic warhead 

### ISSUE THREAD

**Issue by henriquegemignani** [More-Wrong/Factorio-True-Nukes#23]
I disabled all compact variants, as well as all sizes of thermobaric weapons. I'm using Space Exploration.

These are the settings:
![image](https://github.com/More-Wrong/Factorio-True-Nukes/assets/884928/98f877c4-5f01-4ce1-bd9f-d907c5a9a74a)

As a result, nothing unlocks producing Neutron Reflector, which is an ingredient for the 3-stage atomic warhead.

**Comment by More-Wrong** [comment]
Ah, my bad!
I'll change the unlock tree to fix that.

**Comment by henriquegemignani** [comment]
In an attempt to figure out just what little I had to enable, checking "Enable compact 0.1/0.5t warheads" (but not the warheads themselves, oops) caused this error:
![image](https://github.com/More-Wrong/Factorio-True-Nukes/assets/884928/9dd0c0c4-2f5c-49a7-a1e0-834634143032)

**Comment by More-Wrong** [comment]
OK, try the latest version - 0.3.32

**Comment by henriquegemignani** [comment]
The recipe is there. Thanks :)
