### ISSUE TITLE
Crash on any nuke useage.

### ISSUE THREAD

**Issue by Rainnyth** [More-Wrong/Factorio-True-Nukes#9]
Any time I try to use/launch a nuke, I recieve a crash with this message:

The mod True Nukes (0.3.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event True-Nukes::on_tick (ID 0)
Entity creation of entity-ghost failed
stack traceback:
	[C]: in function 'create_entity'
	__True-Nukes__/scripts/blast-system.lua:111: in function 'damage_entity'
	__True-Nukes__/scripts/blast-system.lua:252: in function 'move_blast'
	__True-Nukes__/scripts/blast-system.lua:294: in function 'move_blast'
	__True-Nukes__/scripts/blast-system.lua:294: in function 'move_blast'
	__True-Nukes__/scripts/blast-system.lua:294: in function 'move_blast'
	__True-Nukes__/control.lua:78: in function <__True-Nukes__/control.lua:65>

I am using K2+SE, although neither seem to be the issue? I'm not sure, though. Sorry for the vague details.

**Comment by More-Wrong** [comment]
OK, I think my last release should have fixed this, although its not a very elegant fix.
